export const COLUMNS=[
    {
        Header:"#",
        accessor:"#"
    },
    {
        Header:"Center ID",
        accessor:"center_ID"
    },
    {
        Header:"Shop",
        accessor:"shop"
    },
    {
        Header:"Owner",
        accessor:"owner"
    },
    {
        Header:"Contact",
        accessor:"contact"
    },
    {
        Header:"Email",
        accessor:"emailid"
    },
    {
        Header:"Lattitude",
        accessor:"lattitude"
    },
    {
        Header:"Longitude",
        accessor:"longitude"
    },
    {
        Header:"Address",
        accessor:"address"
    },
    {
        Header:"Landmark",
        accessor:"landmark"
    },
    {
        Header:"State",
        accessor:"state"
    },
    {
        Header:"Country",
        accessor:"country"
    },
    {
        Header:"Profile",
        accessor:"profile"
    },
    {
        Header:"Contact Verified",
        accessor:"contact_verified"
    },
    {
        Header:"Email Verified",
        accessor:"email_verified"
    },
    {
        Header:"Verification Status",
        accessor:"verification_status"
    },
    {
        Header:"Verification Date",
        accessor:"verification_date"
    },
    {
        Header:"Deleted",
        accessor:"deleted"
    },
    {
        Header:"Authorised",
        accessor:"authorised"
    },
    {
        Header:"Created On",
        accessor:"created_on"
    }
]