export const Datatabledata = [
  [
    {
      id: 0,
      "#": "#",
      center_ID: "1",
      shop: "virat",
      owner: "vishal",
      emailid: "vishal@test.com",
      lattitude: "79.5",
      longitude: "78.90",
      address: "shivajinagar pune",
      landmark: "sancheti hospital",
      state: "MAH",
      country: "IND",
      profile: "great",
      contact_verified: "yes",
      email_verified: "yes",
      verification_status: "yes",
      verification_date: "recent",
      deleted: "no",
      authorised: "yes",
      created_on: "today",
    },
    { country: "IND" },
  ],
  [
    {
      id: 1,
      "#": "#",
      center_ID: "1",
      category_name: "dg",
      type: "df",
      options: "wrbsf",
      icons_path: "fg",
      deleted: "ds",
      created_on: "53t",
    },
  ],
  [
    {
      id: 2,
      "#": "#",
      request_id: "erb",
      center_ID: "3",
      center_name: "brsesbz",
      name: "ae",
      contact_numbar: "dfb",
      emailid: "sklsskmf",
      lattitude: "mncmx",
      longitude: "mskfn",
      address: "s,fm,",
      landmark: "s,mf.df",
      state: "s,mfl",
      country: "ashh",
      profile_image: "sbjf",
      deleted: "sf",
      authorised: "sf",
      created_on: "sb",
    },
  ],
];
